apiVersion: v1
kind: ConfigMap
metadata:
  name: myburger-config
  labels:
    app: myburger-config
data:
  JAVA_OPTS: >-
    -server
    -XX:+UseContainerSupport
    -XX:+UseParallelGC
    -XX:MaxRAMPercentage=70.0
    -XX:ActiveProcessorCount=1600
    -XX:+CrashOnOutOfMemoryError
    -Xlog:gc
  DATABASE_URL: "postgresql://postgres:5432/my_burger"
  LOG_LEVEL: "DEBUG"
