apiVersion: v1
kind: Service
metadata:
  name: myvideo-management
spec:
  type: NodePort
  selector:
    app: myvideo-management
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
    - port: 8081
      targetPort: 8081
      nodePort: 30003
