apiVersion: v1
kind: Service
metadata:
  name: myvideo-manager
spec:
  type: LoadBalancer
  selector:
    app: myvideo-manager
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30002
    - name: actuator
      port: 8081
      targetPort: 8081
      nodePort: 30003
