apiVersion: apps/v1
kind: Deployment
metadata:
  name: myvideo-manager
spec:
  selector:
    matchLabels:
      app: myvideo-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: myvideo-manager
    spec:
      containers:
        - name: myvideo-manager
          image: fiapmyburguer/my-video-manager:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "800Mi"
              cpu: "800m"
            requests:
              memory: "512Mi"
              cpu: "600m"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: myvideo-config
            - secretRef:
                name: myvideo-secrets
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/readiness
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
