apiVersion: v1
kind: ConfigMap
metadata:
  name: myvideo-config
  labels:
    app: myvideo-config
data:
  JAVA_OPTS: >-
    -server
    -XX:+UseContainerSupport
    -XX:+UseParallelGC
    -XX:MaxRAMPercentage=70.0
    -XX:ActiveProcessorCount=1600
    -XX:+CrashOnOutOfMemoryError
    -Xlog:gc
  DB_URL: "postgresql://#PG_DB_HOST#:#PG_DB_PORT#/my_video"
  LOG_LEVEL: "INFO"
  NATS_SERVERS: "nats://nats.nats:4222"