name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - feature/create-terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install doctl
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.110.0/doctl-1.110.0-linux-amd64.tar.gz
          tar xf doctl-*.tar.gz
          sudo mv doctl /usr/local/bin

      - name: Authenticate with Digital Ocean
        run: |
          doctl auth init -t ${{ secrets.DO_AUTH_TOKEN }} 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply
        env:
          TF_VAR_do_token: ${{ secrets.DO_AUTH_TOKEN }}
